---

- hosts: all
  become: true
  gather_facts: true
  gather_subset:
    - min
    - '!network'
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  gather_facts: true
  gather_subset:
    - min
    - '!network'
  roles:
    - base

- hosts: workstations
  become: true
  gather_facts: true
  gather_subset:
    - min
    - '!network'
  roles:
    - workstations

- hosts: web_servers
  become: true
  gather_facts: true
  gather_subset:
    - min
    - '!network'
  roles:
    - web_servers

- hosts: db_servers
  become: true
  gather_facts: true
  gather_subset:
    - min
    - '!network'
  roles:
    - db_servers

- hosts: file_servers
  become: true
  gather_facts: true
  gather_subset:
    - min
    - '!network'
  roles:
    - file_servers
